# Generated by Django 3.0.4 on 2020-03-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=20, verbose_name='部位名')),
                ('num_grams', models.IntegerField(max_length=4, verbose_name='グラム数')),
                ('purchase_amt', models.IntegerField(max_length=2, verbose_name='仕入れ量')),
                ('stock_amt', models.IntegerField(max_length=2, verbose_name='在庫数')),
            ],
            options={
                'verbose_name_plural': 'ポストモデル',
            },
        ),
    ]
