# Generated by Django 3.0.4 on 2020-03-08 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='details',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='詳細'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='post',
            name='num_grams',
            field=models.PositiveIntegerField(default=100, verbose_name='グラム数'),
        ),
        migrations.AlterField(
            model_name='post',
            name='purchase_amt',
            field=models.PositiveIntegerField(default=1, verbose_name='仕入れ量'),
        ),
        migrations.AlterField(
            model_name='post',
            name='stock_amt',
            field=models.PositiveIntegerField(editable=False, verbose_name='在庫数'),
        ),
    ]
