# Generated by Django 3.0.4 on 2020-03-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='basashi_sample.jpg', upload_to='', verbose_name='商品画像'),
        ),
    ]
