# Generated by Django 3.0.4 on 2020-03-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_exp_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=20, verbose_name='部位名')),
                ('how_to_eat', models.TextField(blank=True, max_length=50, null=True, verbose_name='賞味方法')),
            ],
            options={
                'verbose_name_plural': '部位モデル',
            },
        ),
    ]
