# Generated by Django 3.0.4 on 2020-03-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_post_part_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.Part', verbose_name='部位'),
        ),
    ]
