# Generated by Django 3.0.4 on 2020-03-23 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_name', models.CharField(max_length=5, verbose_name='都道府県名')),
            ],
            options={
                'verbose_name_plural': '都道府県モデル',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=10, verbose_name='市区町村名')),
                ('pref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.Prefecture', verbose_name='都道府県')),
            ],
            options={
                'verbose_name_plural': '市区町村モデル',
            },
        ),
        migrations.CreateModel(
            name='Chome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chome', models.CharField(max_length=10, verbose_name='丁目')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.City', verbose_name='市区町村')),
            ],
            options={
                'verbose_name_plural': '丁目モデル',
            },
        ),
    ]
