# Generated by Django 3.0.4 on 2020-03-23 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chome',
            options={'verbose_name_plural': '３．丁目モデル'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': '２．市区町村モデル'},
        ),
        migrations.AlterModelOptions(
            name='prefecture',
            options={'verbose_name_plural': '１．都道府県モデル'},
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(default='自宅', max_length=10, verbose_name='住所区分')),
                ('banchi_go', models.CharField(max_length=10, verbose_name='番地・号')),
                ('building', models.CharField(blank=True, max_length=20, null=True, verbose_name='建物')),
                ('chome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.Chome', verbose_name='丁目')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.City', verbose_name='市区町村')),
                ('pref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.Prefecture', verbose_name='都道府県')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': '住所モデル',
            },
        ),
    ]
