# Generated by Django 3.0.4 on 2020-03-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20200324_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='pref',
        ),
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='建物'),
        ),
        migrations.AlterField(
            model_name='address',
            name='chome',
            field=models.CharField(max_length=15, verbose_name='丁目'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=10, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='address',
            name='pref',
            field=models.CharField(max_length=5, verbose_name='都道府県'),
        ),
        migrations.DeleteModel(
            name='Chome',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Prefecture',
        ),
    ]
