# Generated by Django 3.0.4 on 2020-03-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='order_amt',
            field=models.PositiveIntegerField(default=0, verbose_name='購入数'),
        ),
    ]
