# Generated by Django 3.0.4 on 2020-03-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200315_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='住所'),
        ),
    ]
