# Generated by Django 3.0.4 on 2020-03-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200324_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, choices=[('栗原１丁目', '栗原１丁目'), ('谷戸町１丁目', '谷戸町１丁目')], max_length=10, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='住所２'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='building',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='建物'),
        ),
    ]
