# Generated by Django 3.0.4 on 2020-03-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200324_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='pref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Prefecture', verbose_name='都道府県'),
            preserve_default=False,
        ),
    ]
