# Generated by Django 3.0.4 on 2020-03-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_city_pref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.City', verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Prefecture', verbose_name='都道府県'),
        ),
    ]
