# Generated by Django 3.0.4 on 2020-03-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200324_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chome', models.CharField(max_length=10, verbose_name='丁目')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.City', verbose_name='市区町村')),
            ],
            options={
                'verbose_name_plural': '丁目モデル',
            },
        ),
    ]
