# Generated by Django 3.0.4 on 2020-03-23 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_chome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address_2',
        ),
        migrations.AddField(
            model_name='customuser',
            name='banchi_go',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='番地・号'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='chome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Chome', verbose_name='丁目'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, editable=False, max_length=55, null=True, verbose_name='住所'),
        ),
    ]
