# Generated by Django 3.0.4 on 2020-03-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200324_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chome',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.City', verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='city',
            name='pref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Prefecture', verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='chome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Chome', verbose_name='丁目'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.City', verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Prefecture', verbose_name='都道府県'),
        ),
    ]
