# Generated by Django 3.0.4 on 2020-03-23 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('users', '0012_auto_20200324_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='pref',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='chome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.Chome', verbose_name='丁目'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.City', verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.Prefecture', verbose_name='都道府県'),
        ),
        migrations.DeleteModel(
            name='Chome',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Prefecture',
        ),
    ]
