# Generated by Django 3.0.4 on 2020-03-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200324_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='banchi_go',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='building',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='chome',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pref',
        ),
    ]
