# Generated by Django 3.0.4 on 2020-03-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200324_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_icon',
            field=models.ImageField(default='default_user_icon.jpg', upload_to='', verbose_name='ユーザーアイコン'),
        ),
    ]
