# Generated by Django 3.0.4 on 2020-03-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customuser_order_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
