# Generated by Django 3.0.4 on 2020-03-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_delete_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='order_count',
        ),
    ]
