# Generated by Django 3.0.4 on 2020-03-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200309_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stock_amt',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='在庫数'),
        ),
    ]
