# Generated by Django 3.0.4 on 2020-03-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(default='自宅', max_length=10, verbose_name='住所区分')),
                ('pref', models.CharField(max_length=5, verbose_name='都道府県')),
                ('city', models.CharField(max_length=10, verbose_name='市区町村')),
                ('chome', models.CharField(max_length=15, verbose_name='丁目')),
                ('banchi_go', models.CharField(max_length=10, verbose_name='番地・号')),
                ('building', models.CharField(blank=True, max_length=30, null=True, verbose_name='建物')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': '住所モデル',
            },
        ),
    ]
