# Generated by Django 3.0.4 on 2020-03-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=10, verbose_name='サイト名')),
            ],
            options={
                'verbose_name_plural': 'サイト設定モデル',
            },
        ),
    ]
