# Generated by Django 3.0.4 on 2020-03-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='is_selected',
            field=models.BooleanField(default=False, unique=True, verbose_name='有効化'),
        ),
    ]
