# Generated by Django 3.0.4 on 2020-03-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_sitesettings_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(max_length=10, unique=True, verbose_name='サイト名'),
        ),
    ]
