# Generated by Django 3.0.4 on 2020-04-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_icon',
            field=models.ImageField(default='default_user_icon.jpg', upload_to='user_icon', verbose_name='ユーザーアイコン'),
        ),
    ]
