# Generated by Django 3.0.4 on 2020-03-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='注文番号'),
        ),
    ]
