# Generated by Django 3.0.4 on 2020-03-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='注文番号'),
        ),
    ]
