# Generated by Django 3.0.4 on 2020-03-26 19:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0014_auto_20200326_2058'),
        ('orders', '0004_remove_order_order_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderItem',
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': '注文アイテムモデル'},
        ),
    ]
