# Generated by Django 3.0.4 on 2020-03-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200330_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_ended',
            field=models.BooleanField(default=False, editable=False, verbose_name='終了済みか否か'),
        ),
    ]
