# Generated by Django 3.0.4 on 2020-03-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200327_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='in_cart',
            field=models.BooleanField(default=True, editable=False, verbose_name='買い物かごの中か否か'),
        ),
    ]
