# Generated by Django 3.0.4 on 2020-03-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_has_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ステータス'),
        ),
    ]
