# Generated by Django 3.0.4 on 2020-03-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200310_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(default=100, verbose_name='価格'),
            preserve_default=False,
        ),
    ]
