# Generated by Django 3.0.4 on 2020-03-23 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='exp_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='商品期限'),
        ),
    ]
