# Generated by Django 3.0.4 on 2020-03-25 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200324_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='exp_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='消費期限'),
        ),
    ]
