# Generated by Django 3.0.4 on 2020-04-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200326_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='basashi_sample.jpg', upload_to='post_img/', verbose_name='商品画像'),
        ),
    ]
